### ISSUE TITLE
Nomenclatura de ficheros

### ISSUE THREAD

**Issue by aseguragonzalez** [palolo25/pruebas-en-html#1]
# Introducción

Por lo general cualquier, todos los proyectos deben tener defina una nomenclatura (_name convention rules_) tanto para la codificación como para ficheros y directorios. En este caso, una página web se recomienda las siguientes reglas básicas:

- Nombres de directorios y ficheros siempre en minúsculas utilizando notación kebab-case (pagina-de-prueba.html)
- Debe existir un fichero index.html que es la página principal.
- NUNCA se utilizan espacios en blanco en los nombres de ficheros o directorios.
- Los recursos como imágenes, audio, ficheros de estilo deben tener su propio subdirectorio en el directorio assets
- Una posible estructura de ficheros es:

```text
+ assets/
  + images/
  + videos/
  + audios/
  + scripts/
    - main.js
  + styles/
    - main.css
   - favico.ico
- index.html
```

Tareas:
- [ ] Actualizar todos los nombres de ficheros y directorios.
- [ ] Actualizar los enlaces entre ficheros
- [ ] Construir árbol de directorios
- [ ] Extraer fichero de estilos CSS

**Comment by palolo25** [comment]
creo que ya estaria @aseguragonzalez

**Comment by aseguragonzalez** [comment]
# Correcciones V2

No está correctamente resuelta la issue. Te explico:

## Index.html

Cuando digo que debe existir un fichero principal index.html, en este caso deberías renombrar JUEGAGOLFF.html (está mal escrito)

## PAGINADEPRUEBA.html

Si no tiene relevante, se elimina. Si tiene ejemplos de pruebas interesantes, hay que renombrarlo con la nomenclatura especificada: minúsculas y palabras separadas por guiones: kebab-case => pagina-de-pruebas.html

## ESCRITOSENMARKDOWN

Tampoco ha sido actualizado con la nomenclatura específica. Además, debería tener un nombre más "adecuado", por ejemplo, se suele utilizar `docs` para el directorio de documentación del proyecto.  Lo mismo pasa con las carpetas de los apuntes de html, vscode y sus respectivos dicheros md.

Como no hay muchos documentos, se podría utilizar:

Opción 1:

+ docs/
  + html/
     - apuntes-de-html.md
  + vscode/ 
     - comandos-para-vscode.md
 
Opción 2:
 + docs/
     - html.md
     - vscode.md

## styles

El directorio styles debe estar en assets como se indicaba en el diagrama del árbol de directorios. Además, no es necesario que tenga un subdirectorio CSS ya que styles ya comprende cualquier fichero *.CSS. En cualquier caso, esa subcarpeta TAMPOCO debe ir en mayúsculas, como ninguna carpeta/directorio, tal y como se ha descrito en las reglas de nomenclatura.

## Estilos-de-juegagolff.css

El documento no sigue las reglas de nomenclatura:
1. Debe estar en minúsculas: estilos-de-juegagolff.css
2. `juegagolff` son dos palabras (mal escritas) por lo que debería ser: juega-golf.css

** RECUERDA **

Debes acostumbrarte a trabajar con `Pull Request` y no hacer cambios en `main` directamente

** TENER EN CUENTA **

Para cambiar el nombre de un directorio o fichero en el que el cambio solo difiere entre mayúsculas y minúsculas, es necesario hacerlo en dos pasos para que git (en windows) detecte el cambio y lo replique en el repositorio remoto. Por ejemplo:

Nombre original: `AUDIO/`:

```shell
# pasamos a minúsculas el nombre del directorio audio añadiendo un caracter para forzar que detecte el cambio
$ mv AUDIO audio2
# agregamos los cambios
$ git add .
# confirmamos los cambios
$ git commit -m "actualizado nombre del directorio: paso 1"
# actualizamos la rama del repositorio remoto
$ git push origin tu-rama-de-tarea
# modificamos nuevamente el nombre del directorio al nombre final deseado
$ mv audio2 audio
# agregamos los cambios
$ git add .
# confirmamos los cambios
$ git commit -m "actualizado nombre del directorio: paso 2"
# actualizamos la rama del repositorio remoto
$ git push origin tu-rama-de-tarea
```

**Comment by aseguragonzalez** [comment]
# Hoja de estilos

Revisando el código del fichero css hay dos errores:

## Comentarios

Los ficheros no empiezan con una frase, nombre o descripción `tal cual`. Si queremos incluir información descriptiva debe ir en un comentario:

**MAL**
```css
Estilos de juegagolff
.busca{
    color: rgb(255, 255, 255);
    background-color: rgb(5, 218, 5);
    font-size: 300%;
    font-style: normal;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
text-align: center;
}
```

**BIEN**
```css
/* Estilos de juegagolff */
.busca{
    color: rgb(255, 255, 255);
    background-color: rgb(5, 218, 5);
    font-size: 300%;
    font-style: normal;
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    text-align: center;
}
```

## Indentación

Los documentos deben estar correctamente indentados. Para ello hay disponibles atajos de teclado (shortcuts) que automatizan esta tarea. En el caso de `vscode` el shorcut es `shift+Alt+f`. Si no surte efecto y es visible que no está bien indentado, seguramente hay errores y debes buscarlos, por ejemplo en la línea 56:

```css
#Norg{
    color: rgb(255, 255, 255);
    font-size: smaller;
    font-family: 'Times New Roman', Times, serif;
    text-align: right
    vertical-align: middle;
}
```
